### ISSUE TITLE
Line numbers are clipped on Firefox

### ISSUE THREAD

**Issue by captn3m0** [labmlai/annotated_deep_learning_paper_implementations#62]
Screenshot for https://nn.labml.ai/cfr/index.html#section-0

![image](https://user-images.githubusercontent.com/584253/123048129-95457880-d3ed-11eb-87eb-da2caff68725.png)

Using Firefox 89.0.1 (64-bit) on Linux

Removing the width from `.lineno` seems to fix it:

```css
span.lineno {
    width: 20px;
}
```

Doesn't seem to have an impact on Chrome.

**Comment by vpj** [comment]
A better solution is to increase the width to something like `25px`. Can you try and see if it works on firefox? Because if we remove the width there will be an alignment problem because the line numbers will have different number of digits and hence different widths.

Can include something like `white-space: nowrap` to make sure it doesn't get split into two lines.

**Comment by captn3m0** [comment]
`white-space: nowrap` fixes it as well, I'll update the PR.
