### ISSUE TITLE
Stride Issue in ResNet?

### ISSUE THREAD

**Issue by zwqnju** [labmlai/annotated_deep_learning_paper_implementations#83]
https://github.com/labmlai/annotated_deep_learning_paper_implementations/blob/b10e3dea2c7e1f6569bfdf8e1a48f8d48b5a645d/labml_nn/resnet/__init__.py#L286-L288

Your annotation in the above code says: "The first block for the new feature map size, will have a stride length of 2, except fro the very first block". 

On the contrary, your implementaion means the first convolution of the very first block has a stride of 2, and the first convolution of other blocks have a stride of 1. I think this is an issue.

**Comment by zwqnju** [comment]
Another question, in the original ResNet paper, there is a max pooling layer before the first residual block. It doesn't exist in your implementation, why?

**Comment by vpj** [comment]
A block consists of a few convolution layers https://nn.labml.ai/resnet/index.html#section-8

https://github.com/labmlai/annotated_deep_learning_paper_implementations/blob/master/labml_nn/resnet/__init__.py#L119-L141

The first convolution layer and the projection for shortcut has a stride of 2 or 1. The other convolution layer always have a stride of 1.

This loop adds multiple blocks in series.
https://github.com/labmlai/annotated_deep_learning_paper_implementations/blob/master/labml_nn/resnet/__init__.py#L285-L308

On each iteration `i` of the outer loop it adds `n_blocks[i]` number of blocks with `channels` number of channels. All the blocks of a single iteration have same feature map size.

The first block of a feature map size will have a stride length of `2` and the next `n_blocks[i] - ` blocks will have a stride length `1`.

And the very first block `i = 0` will also have a stride of `1`.

I feel the description is correct. May be there is a better way to phrase it.

**Comment by vpj** [comment]
As for the pooling layer, this implementation was for CIFAR-10 dataset. The paper says the feature map sizes are 32x32, 16x16 and 8x8 (section 4.2) which implies there is no pooling layer and that the initial convolution layer (before the residual blocks) has a stride of 1, since the image size is also 32x32.

**Comment by vpj** [comment]
About the max pooling layer, the paper mentions that the feature map sizes are 32x32, 16x16 ... for CIFAR-10 implementation in section 4.2. Since the image size is 32x32 this means that either the very first convolution layer has a stride length of 1 or that they omitted the max pooling. We chose to omit max pooling because they don't mention that in section 4.2.

While going through the code again to look at your question i figured we had a mistake where the initial convolution had a stride of 1 which i changed to 2. Thanks.

I feel that you would need the max pooling layer for larger images while it's not necessary since we are dealing with much smaller image sizes (32x32 vs 112x112).

**Comment by vpj** [comment]
Closing the issue
