### ISSUE TITLE
Colors in the paper annotation 

### ISSUE THREAD

**Issue by lolipopshock** [labmlai/annotated_deep_learning_paper_implementations#97]
Hi team labml! Thanks for the great project -- really helpful for the community. It's also great that you've provided annotations for the [papers](https://github.com/labmlai/annotated_deep_learning_paper_implementations/tree/master/papers) -- just wondering: are there explanations for how to interpret the highlight color used in the PDF files? Thanks!

**Comment by vpj** [comment]
We try to highlight a single point (or a single concept) in the same color. We rotate and reuse the colors (e.g. we might use yellow to highlight the benefits of the proposed model on page 1, and reuse yellow again on page 3 for something else).

We just started highlighting papers for our reading sessions. Few of us were doing it and others started following the practice because it makes it easier to navigate the paper during the reading sessions. We still have no formal way of highlighting and everyone does a little differently. We shared highlighted papers a lot later and learned that people find them useful. So now we put a little extra effort into highlighting/annotating to make them useful for a wider audience.

Please let us know if you have any suggestions for improvements.

And, thank you for LayoutPapers! We've been looking at using it to extract figures from papers for [papers.labml.ai](https://papers.labml.a). It looks much better than the current model/algorithm we use right now.

**Comment by lolipopshock** [comment]
Thank you @vpj very much for the clarification! And it's great to learn that layoutparser can be helpful for your task! And please let me know if you need any assistance or have questions when using layoutparser :)
